use std::fmt;
use std::str::FromStr;

use crate::object::ObjectType;

/// A content-addressed object ID: `BLAKE3_keyed(chunk_id_key, type ‖ payload)`.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Id(pub [u8; 32]);

/// The repo's `chunk_id_key`: 32 random bytes generated by `ctm init`.
#[derive(Clone, PartialEq, Eq)]
pub struct RepoKey(pub [u8; 32]);

impl Id {
    /// The ID of an object with this type and (uncompressed, unencrypted) payload.
    pub fn compute(key: &RepoKey, ty: ObjectType, payload: &[u8]) -> Id {
        let mut h = blake3::Hasher::new_keyed(&key.0);
        h.update(&[ty as u8]);
        h.update(payload);
        Id(*h.finalize().as_bytes())
    }

    pub fn to_hex(&self) -> String {
        hex::encode(self.0)
    }
}

impl fmt::Display for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex())
    }
}

impl fmt::Debug for Id {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Id({})", &self.to_hex()[..12])
    }
}

#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[error("not a 64-character lowercase hex object ID")]
pub struct ParseIdError;

impl FromStr for Id {
    type Err = ParseIdError;

    fn from_str(s: &str) -> Result<Id, ParseIdError> {
        if s.len() != 64 || s.bytes().any(|b| b.is_ascii_uppercase()) {
            return Err(ParseIdError);
        }
        let mut id = [0u8; 32];
        hex::decode_to_slice(s, &mut id).map_err(|_| ParseIdError)?;
        Ok(Id(id))
    }
}

impl fmt::Debug for RepoKey {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str("RepoKey(..)")
    }
}
